language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "iojs"
before_install:
  - "npm install"
  - "npm install daemon"
  - "npm install commander"
  - "npm install mocha -g"
  - "npm install jslint -g"
  - "bin/dsweeper -p `pwd`/test/fixtures/sweep_me -d -t test-dsweeper"
